# Generated by Django 3.1.1 on 2020-09-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19dailydata',
            name='report_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='covid19totaldata',
            name='report_date',
            field=models.DateField(),
        ),
    ]
