# Generated by Django 3.1.1 on 2020-09-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200902_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19dailydata',
            name='number_of_deaths_for_today',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid19dailydata',
            name='number_of_patients_for_today',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid19dailydata',
            name='number_of_recovered_patients_for_today',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid19dailydata',
            name='number_of_tests_for_today',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid19totaldata',
            name='number_of_seriously_ill_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid19totaldata',
            name='pneumonia_rate_in_patients',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid19totaldata',
            name='total_number_of_deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid19totaldata',
            name='total_number_of_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid19totaldata',
            name='total_number_of_recovered_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covid19totaldata',
            name='total_number_of_test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
