# Generated by Django 3.1.1 on 2020-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200903_0706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Covid19TotalData',
        ),
        migrations.AddField(
            model_name='covid19dailydata',
            name='number_of_seriously_ill_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covid19dailydata',
            name='pneumonia_rate_in_patients',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covid19dailydata',
            name='total_number_of_deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covid19dailydata',
            name='total_number_of_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covid19dailydata',
            name='total_number_of_recovered_patients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='covid19dailydata',
            name='total_number_of_test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
